### PR TITLE
Remove dependency from rootpy

### PR DESCRIPTION
**Pull request by dpiparo**
Hi,

this PR should remove the need for rootpy. I think the package is a really nice tool, I am just submitting this to make the converter thinner.
Btw, I am still unable to run the testsuite.

Cheers,
       Danilo

### CODE REVIEW

**Comment by GraemeWatt** [comment]
Thanks a lot, Danilo!  I agree that it's simpler to use the PyROOT bindings rather than the third-party rootpy.  I was planning to look into making the changes myself, but thanks for saving me the trouble.

To run the testsuite on the command line, I use the command from the `.travis.yml` file:
```coverage run -m unittest discover hepdata_converter/testsuite 'test_*'```
Currently the build is failing with:
```AttributeError: type object 'ROOT' has no attribute 'TFile'```

**Comment by dpiparo** [comment]
Hi Graeme,

I understand where the (obvious) mistake is and I can also run the tests locally now.
On the other hand there are rather intrusive changes to be put into the tool to use simple ROOT histograms. I have done some of the work. Do you think we can iterate, also privately, to finish the task? It is a bit difficult to put the ends in the code as it is a bit obscure, although perfectly working.

**Comment by dpiparo** [comment]
All tests fixed for my local execution. Adapt code to accommodate the usage of simple ROOT objects instead of the rootpy wrappers.

**Comment by dpiparo** [comment]
Hi,

it seemed that the remaining issues have been ironed out.

Danilo

**Pull request merged**
