### PR TITLE
Remove numpy dependencies, update ROOT installation instructions

### PR DESCRIPTION
**Pull request by dpiparo**
Hi,

I took the freedom to update the ROOT installation instructions and to remove an unnecessary numpy dependency.
The latter change has the advantage of making the package slimmer and more easily included in distributions like the LCG releases.

Cheers,
        D

### CODE REVIEW

**Comment by eamonnmag** [comment]
Thanks Danilo! I was just going to reply to your issue :) it's good to have your input in this since I'm in no way a ROOT expert.

**Comment by dpiparo** [comment]
Hi Eammon,

thanks a lot. As you can see I amended my PR: we needed double precision for graphs. Let's see what travis says. Do you know how to run the tests locally in order to avoid this kind of simple mistakes?

D

**Comment by eamonnmag** [comment]
I think just python setup.py test

Need to check for sure. But it's that or py.test. Some of the tools have
slightly different test setups while we understood which one suited us
better. So we have pyunittest and also pytest.

**Comment by dpiparo** [comment]
Thanks a lot. For this round it was rather obvious. Travis is happy ;-)

**Pull request merged**
